### ISSUE TITLE
Documentation: no parallel socket operations on AF_KTLS and bound socket are possible without explicit synchronization

### ISSUE THREAD

**Issue by fridex** [ktls/af_ktls#25] opened 2016-04-25 13:04 UTC
Bound UDP/TCP sockets should be locked while we are doing operations in AF_KTLS since (not only) userspace can operate on them in parallel with AF_KTLS and that could lead to inconstancy; pseudocode:

```
in AF_KTLS:                                   userspace:
read(sd, ktls_buf, size, MSG_PEEK)

decrypt                                         !!! read(sd, buf2, size, 0)

!!! pop_record(sd)

```

**Comment by fridex** [comment] 2016-04-25 13:07
related: https://github.com/fridex/af_ktls/issues/21

**Comment by fridex** [comment] 2016-04-25 14:27
Since socket locking is done inside socket operations (binded socket), we cannot lock it in AF_KTLS. Synchronization has to be done explicitly in user space if necessary. So this should be considered as "not a bug", but it *should be* explicitly stated in documentation.

**Comment by djwatson** [comment] 2016-08-17 19:09
Not a bug.  Closing

**Closed by djwatson** 2016-08-17 19:09 UTC
